#
language: java
jdk: oraclejdk8
branches:
  only:
    - develop
install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script:
  - mvn -P${TRAVIS_BRANCH} clean install

# normally also deploy , but that's not ready yet
